# Generated by Django 2.2.2 on 2019-06-22 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ElectoralCort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField(max_length=255)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='VoteCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
                ('private_key', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
                ('voted', models.BooleanField(default=False)),
                ('time_stamp', models.DateField(auto_now=True)),
                ('credential', models.CharField(max_length=10, unique=True)),
                ('ci', models.CharField(max_length=10, unique=True)),
                ('enable_vote', models.BooleanField(default=False)),
                ('circuit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SDCore.Circuit')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SDCore.Candidate')),
            ],
        ),
        migrations.AddField(
            model_name='circuit',
            name='vote_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SDCore.VoteCenter'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='political_party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SDCore.PoliticalParty'),
        ),
    ]
