# Generated by Django 2.2.2 on 2019-06-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDCore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncriptedVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encripted_vote', models.TextField()),
            ],
        ),
    ]
