# Generated by Django 2.2.2 on 2019-06-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDCore', '0003_auto_20190623_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
